version: '3.8'

services:
  frontend:
    image: jhhyeony/club-frontend
    container_name: club-frontend
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - express-server
    networks:
      - reverse-net

  express-server:
    image: jhhyeony/club-backend
    container_name: express-server
    env_file:
      - .env.production
    ports:
      - "5050:5000"
    restart: always
    networks:
      - reverse-net

volumes:
  mysql-data:
    external: true
    name: pda_website_mysql-data

networks:
  reverse-net:
    external: true

